{application,khepri,
             [{description,"Tree-like replicated on-disk database library"},
              {vsn,"0.18.0"},
              {registered,[khepri_sup,khepri_event_handler]},
              {applications,[kernel,stdlib,compiler,ra,horus]},
              {env,[]},
              {mod,{khepri_app,[]}},
              {files,["README.md","LICENSE-Apache-2.0","LICENSE-MPL-2.0",
                      "mix.exs","rebar.config","rebar.lock","src","include"]},
              {modules, ['khepri','khepri_adv','khepri_app','khepri_cluster','khepri_condition','khepri_event_handler','khepri_evf','khepri_export_erlang','khepri_import_export','khepri_machine','khepri_machine_v0','khepri_path','khepri_pattern_tree','khepri_payload','khepri_prefix_tree','khepri_projection','khepri_sproc','khepri_sup','khepri_tree','khepri_tx','khepri_tx_adv','khepri_utils']},
              {licenses,["Apache-2.0","MPL-2.0"]},
              {links,[{"GitHub","https://github.com/rabbitmq/khepri"}]},
              {build_tools,["rebar3","mix"]},
              {doc,"doc"}]}.
