{application,khepri_mnesia_migration,
             [{description,"Tools to migrate between Mnesia and Khepri"},
              {vsn,"0.8.1"},
              {registered,[khepri_mnesia_migration_sup,m2k_cluster_sync_sup]},
              {mod,{khepri_mnesia_migration_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {files,["README.md","LICENSE-Apache-2.0","LICENSE-MPL-2.0",
                      "mix.exs","rebar.config","rebar.lock","src"]},
              {modules, ['khepri_mnesia_migration_app','khepri_mnesia_migration_sup','kmm_utils','m2k_cluster_sync','m2k_cluster_sync_sup','m2k_export','m2k_subscriber','m2k_table_copy','m2k_table_copy_sup','m2k_table_copy_sup_sup','mnesia_to_khepri','mnesia_to_khepri_converter','mnesia_to_khepri_example_converter']},
              {licenses,["Apache-2.0","MPL-2.0"]},
              {links,[{"GitHub",
                       "https://github.com/rabbitmq/khepri_mnesia_migration"}]},
              {build_tools,["rebar3","mix"]},
              {doc,"doc"}]}.
